blog/urls.py
from django.urls import path

from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='blog_view'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
]

catalog/urls.py
from django.urls import path

from catalog.views import ProductListView, ProductDetailView, ProductTemplateView, ProductDeleteView, ProductCreateView, \
    ProductUpdateView
from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('contacts/', ProductTemplateView.as_view(), name='contacts'),
    path('create/', ProductCreateView.as_view(), name='create_product'),
    path('view/<int:pk>/', ProductDetailView.as_view(), name='view_product'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    path('edit/<int:pk>/', ProductUpdateView.as_view(), name='edit_product'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='категория продукта')
    description = models.TextField(null=True, blank=True, verbose_name='описание продукта')

    def __str__(self):
        return f'{self.name} {self.description}'

    class Meta:
        verbose_name = 'категория продукта'
        verbose_name_plural = 'категории продуктов'
        ordering = ('name',)


class Product(models.Model):
    name = models.CharField(max_length=200, unique=True, verbose_name='название продукта')
    description = models.TextField()
    image = models.ImageField(upload_to='product/', null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=15, decimal_places=2, verbose_name='цена')
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return f'{self.name} {self.image} {self.price} {self.created_at} {self.updated_at}'

    class Meta:
        verbose_name = 'название продукта'
        verbose_name_plural = 'названия продуктов'
        ordering = ('-name',)


class ProductVersion(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    version_number = models.IntegerField(verbose_name='версия №')
    version_name = models.CharField(max_length=150, verbose_name='имя версии')
    current_version = models.BooleanField(default=True, verbose_name='активная версия')

    def __str__(self):
        return f'{self.product} {self.version_number} {self.version_name}'

    class Meta:
        verbose_name = 'связь'
        verbose_name_plural = 'связи'

catalog/forms.py
from django import forms

from catalog.models import Product, ProductVersion


class StyleMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-check-input'


class ProductForm(StyleMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def clean_name(self):
        words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        cleaned_data = self.cleaned_data['name']
        for word in words:
            if word in cleaned_data.lower():
                raise forms.ValidationError('Запрещенные слова ' + word)
        return cleaned_data

    def clean_description(self):
        words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        cleaned_data = self.cleaned_data['description']
        for word in words:
            if word in cleaned_data.lower():
                raise forms.ValidationError('Запрещенные слова ' + word)
        return cleaned_data


class ProductVersionForm(StyleMixin, forms.ModelForm):
    class Meta:
        model = ProductVersion
        fields = '__all__'

catalog/views.py
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, TemplateView, DeleteView, CreateView, UpdateView

from catalog.forms import ProductForm, ProductVersionForm
from catalog.models import Product, ProductVersion


class ProductListView(ListView):
    model = Product
    extra_context = {'title': 'Главная'}

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        products = Product.objects.all()

        for products_key in products:
            version = ProductVersion.objects.filter(product=products_key)
            acive_version = version.filter(current_version=True).first()
            products_key.active_version = acive_version.product if acive_version else 'Версия не активна'
        context['products'] = products

        return context


class ProductDetailView(DetailView):
    model = Product
    extra_context = {'title': 'Описание'}


class ProductTemplateView(TemplateView):
    extra_context = {'title': 'Контакты'}
    template_name = 'catalog/contacts.html'


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:home')


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, ProductVersion, form=ProductVersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, ProductVersion, form=ProductVersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('catalog:view_product', args=[self.kwargs.get('pk')])

catalog/templates/catalog/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:list' %}">Блог</a>
    </nav>
</div>

{% include 'catalog/includes/inc_main.html' %}

<div class="container">
    {% block content %}
    {% endblock%}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row text-start">
    <div class="col-lg-9 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <table class="table table-striped">
                    <tr>
                        <td class="w-25">Страна</td>
                        <td>USA</td>
                    </tr>
                    <tr>
                        <td class="w-25">ИНН</td>
                        <td>91-1144442</td>
                    </tr>
                    <tr>
                        <td class="w-25">Адрес</td>
                        <td>Redmond,WA,98052-6399</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name">Имя</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                    </div>
                    <div class="mb-3">
                        <label for="phone">Телефон</label>
                        <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон"
                               required>
                    </div>
                    <div class="mb-3">
                        <label for="message">Сообщение</label>
                        <textarea type="text" name="message" class="form-control" id="message"
                                  placeholder="Введите сообщение" required></textarea>
                    </div>
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/goods.html
{% extends 'catalog/base.html' %}
{% load media_path %}

{% block content %}
<div class="row text-center">
    <div class="col-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
            </div>
            <div class="card-body">
<!--                <img src="/media/{{ object.image }}" class="mb-4 mt-4">-->
                <img src="{{ object.image | path_media }}" class="mb-4 mt-4">
                <h4 class="card-title pricing-card-title">{{ object.price }} руб</h4>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>- Категория {{ object.category.name }}</li>
                    <li>- Описание: {{ object.description }}</li>
                </ul>
                <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row text-center">
    {% for object in objects%}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ object.name|truncatechars:35 }}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>- Описание: {{ object.description|truncatechars:100 }}</li>
                </ul>

                <a href="{% url 'catalog:goods' object.pk %}" type="button"
                   class="btn btn-lg btn-block btn-outline-primary">Описание</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock%}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить продукт {{ object.name }}? </p>
                        <button type="submit" class="btn btn-danger">
                            Подтвердить
                        </button>
                        <a href="{% url 'catalog:home' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load media_path %}

{% block content %}
<div class="row text-center">
    <div class="col-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
            </div>
            <div class="card-body">
                <!--                <img src="/media/{{ object.image }}" class="mb-4 mt-4">-->
                <img src="{{ object.image | path_media }}" class="mb-4 mt-4">
                <h4 class="card-title pricing-card-title">{{ object.price }} руб</h4>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>- Категория {{ object.category.name }}</li>
                    <li>- Описание: {{ object.description }}</li>
                </ul>
                <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                <a href="{% url 'catalog:delete_product' object.pk %}" type="button"
                   class="btn btn-lg btn-block btn-outline-danger ms-2">Удалить</a>

            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<form method="post" enctype="multipart/form-data">
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">

                        {% csrf_token %}
                        <!--                        {{ form.as_p }}-->
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-success mt-3">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>

                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">
                            Версии продуктов
                        </h4>
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                        <!--                            {{ form.as_p }}-->
                        {{ form|crispy }}
                        <div class="card box-shadow mb-3 mt-4"></div>
                        {% endfor %}

                        </button>

                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<a href="{% url 'catalog:create_product' %}" type="button" class="btn btn-success mb-4">Создать продукт</a>
<div class="row text-center">
    {% for object in products %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ object.name|truncatechars:35 }}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>- Описание: {{ object.description|truncatechars:100 }}</li>
                    <li>- Активная версия: <strong>{{ object.active_version }}</strong></li>
                </ul>
                <a href="{% url 'catalog:view_product' object.pk %}" type="button"
                   class="btn btn-lg btn-block btn-outline-primary">Описание</a>
                <a href="{% url 'catalog:edit_product' object.pk %}" type="button"
                   class="btn btn-lg btn-block btn-outline-primary">Изменить</a>

            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock%}